services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 58318:1972
      - 58316:52773
      - 58317:53773
      - 19999:9999
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    networks:
      - default

  jupyter:
    # image: quay.io/jupyter/base-notebook
    image: quay.io/jupyter/base-notebook:python-3.11.10
    user: root
    ports:
      - 29999:8888
    volumes:
      - ./jupyter:/home/jovyan/work
    environment:
      - NB_UID=${UID:-1000}
      - NB_GID=${GID:-1000}
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=$OPENAI_API_KEY
    command: start-notebook.sh --NotebookApp.token=''
    networks:
      - default

networks:
  default:
    driver: bridge