services:
  iris:
    container_name: dc-facilis-iris-1
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 58318:1972
      - 58316:52773
      - 58317:53773
      - 19999:9999
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - AI_ENGINE=$AI_ENGINE
      - API_KEY=$API_KEY
    networks:
      - default
    
  streamlit:
    container_name: dc-facilis-frontend-1
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - 8501:8501
    volumes:
      - ./python/facilis/:/app/
    networks:
      - default

networks:
  default:
    driver: bridge