services:
  iris:
    container_name: dc-facilis-iris-1
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 58318:1972
      - 58316:52773
      - 58317:53773
      - 19999:9999
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - AI_ENGINE=$AI_ENGINE
      - API_KEY=$API_KEY
      - LLM_MODEL_NAME=$LLM_MODEL_NAME
    networks:
      - default
    
  streamlit:
    container_name: dc-facilis-frontend-1
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - 8501:8501
    volumes:
      - ./python/facilis/:/app/
    networks:
      - default

  jupyter:
    image: quay.io/jupyter/base-notebook
    ports:
      - 39999:8888
    volumes:
      - ./jupyter:/home/jovyan/work
    environment:
      - AI_ENGINE=$AI_ENGINE
      - API_KEY=$API_KEY
      - LLM_MODEL_NAME=$LLM_MODEL_NAME
    command: ["start-notebook.py", "--NotebookApp.token='123'"]
    networks:
      - default

networks:
  default:
    driver: bridge