gather_task:
  description: >
    I want you to create a comprehensive city guide.
    This guide should provide a thorough overview of what
    the city has to offer, including hidden gems, cultural
    hotspots, and must-visit landmarks.

    Trip Date: {range}
    Traveling from: {origin}
    Traveling to: {city}
    Traveler Interests: {interests}
  expected_output: >
    The final answer must be a comprehensive city guide,
    rich in cultural insights and practical tips,
    tailored to enhance the travel experience.

plan_task:
  description: >
    Expand this guide into a a full 1-day travel
    itinerary with detailed per-day plans, including
    weather forecasts, places to eat, packing suggestions,
    and a budget breakdown.

    You MUST suggest actual places to visit, actual hotels
    to stay and actual restaurants to go to.

    Trip Date: {range}
    Traveling from: {origin}
    Traveling to: {city}
    Traveler Interests: {interests}
  expected_output: >
    Your final answer MUST be a complete expanded travel plan,
    formatted as markdown, encompassing a daily schedule,
    anticipated weather conditions, recommended clothing and
    items to pack, and a detailed budget, ensuring THE BEST
    TRIP EVER, Be specific and give it a reason why you picked.